version: '3.8'
services:
  db:
    image: mysql:5.6
    container_name: yogadb
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: db_inyogaday
      MYSQL_USER: yogauser123
      MYSQL_PASSWORD: YogaDay123@HitpL2023
    ports:
      - "3307:3306"
    networks:
      - tomcat-network-yoga
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s
  tomcat:
    build:
      context: ./Docker-file/app
    image: javaapp
    container_name: yogaapp
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      CATALINA_OPTS: "-Xms64m -Xmx128m -XX:+UseContainerSupport -XX:MaxRAMPercentage=30.0"
      MYSQL_HOST: db
      MYSQL_PORT: 3307
      MYSQL_DB: db_inyogaday
      MYSQL_USER: yogauser123
      MYSQL_PASSWORD: YogaDay123@HitpL2023
    ports:
      - "8084:8080"
    networks:
      - tomcat-network-yoga

  nginx:
    image: nginx:latest
    container_name: yoga-nginx
    restart: always
    ports:
      - "8085:80"
      - "445:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - tomcat
    networks:
      - tomcat-network-yoga


networks:
  tomcat-network-yoga:  # Custom network for communication between Tomcat and MySQL
    driver: bridge
